### ISSUE TITLE
new shadernodes

### ISSUE THREAD

**Issue by shivamcv** [jesterKing/CCSycles#46]
can you please add these shader nodes 

VECT_MATH
BSDF_VELVET
HUE_SAT
BRIGHTCONTRAST
VALTORGB
HOLDOUT

**Comment by jesterKing** [comment]
These nodes will be added. I'll be creating separate issues for each node for easier tracking of work done.

Regarding output on session.scene reset, please report it in a separate issue.

**Comment by jesterKing** [comment]
Added separate issues #52 #53 #54 #55 #56 and #57
