### ISSUE TITLE
Could not Build

### ISSUE THREAD

**Issue by oschakravarthi** [jesterKing/CCSycles#73]
Hi,

I am using VS 2017 Community.
I have downloaded boost_1_60_0-msvc-14.0-64.exe from the page https://sourceforge.net/projects/boost/files/boost-binaries/1.60.0/

I have extracted it and copied the extracted content to boost folder in my CCSycles folder.
The contents of the folder looks like this.
 
![image](https://user-images.githubusercontent.com/29388049/57050915-6e230e80-6c9c-11e9-8f6c-b2434f420367.png)

When I try to build CCSycles, I am getting the errors shown in the below screenshot.

![image](https://user-images.githubusercontent.com/29388049/57050969-bc381200-6c9c-11e9-93ca-9b587f8b57c4.png)

What am I doing wrong? Please help me in building the solution.

Thanks in advance

**Comment by jesterKing** [comment]
Hey, you should use the https://github.com/mcneel/CCSycles repository instead. This repository is very much out of date.
